apiVersion: v1
kind: ConfigMap
metadata: 
    name: database-configmap
data: 
    MYSQL_DATABASE_HOST: mysql-service.default.svc.cluster.local
    MYSQL_USER: clarus
    MYSQL_DATABASE: phonebook